version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      NODE_ENV: production
    ports:
      - 3000:80

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:5000
